[package]
name = "osm_area_extractor_rs"
version = "0.1.0"
authors = ["Filip Krumpe <filip.krumpe@fmi.uni-stuttgart.de>"]
edition = "2018"

[lib]
name = "library"
path = "src/lib.rs"

[dependencies]
osmpbfreader = "0.12.0"
rayon = "1.0.3"
clap = "2.32.0"